name: "GPTZeroShot on whisper"
model: "GPTZeroShot"
data: "ADReSS_with_PITT_audio"
cv_splits: 10
preprocessors:
  - "PAR segmentation"
  - "ASR whisper"
config_data:
  keep_terminators: True
config_gpt:
  model: 'gpt-4o-mini-2024-07-18'
